apiVersion: v1
kind: Pod
metadata:
  name: my-stores
  labels:
    app: myStore

spec:
  containers:
  - name: basu-stores
    image: bainapur/webserver:0.0.7
    ports:
    - containerPort: 5000
    volumeMounts:
        - name: mango-settings
          mountPath: /etc/config
    env:
    - name: MANGO_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key : mango-username
    - name: MANGO_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key : mango-password
  volumes:
  - name: mango-settings
    configMap:
      name: mango-settings
